### ISSUE TITLE
运行用例提示错误result.tb_locals = self.tb_locals

### ISSUE THREAD

**Issue by macxiao** [debugtalk/ApiTestEngine#11]
安装成功后，运行任何用例都是提示如下错误：
Michael@MichaeldeMacBook-Pro:~/Downloads/ApiTestEngine-0.2.2$ ate test.yml
Traceback (most recent call last):
  File "/usr/local/bin/ate", line 9, in <module>
    load_entry_point('ApiTestEngine==0.2.2', 'console_scripts', 'ate')()
  File "build/bdist.macosx-10.11-x86_64/egg/ate/cli.py", line 53, in main
  File "/Users/Michael/Downloads/ApiTestEngine-master/src/pyunitreport/PyUnitReport/runner.py", line 42, in run
    result.tb_locals = self.tb_locals
AttributeError: 'HTMLTestRunner' object has no attribute 'tb_locals'

**Comment by debugtalk** [comment]
[bugfixed.](https://github.com/debugtalk/PyUnitReport/commit/352215534c9ce756ead4562fbb0f6beaac47b1b0)
