### ISSUE TITLE
对系统、版本啥的有要求吗? 单独运行 test_apiserver.py, multiprocessing启动服务器的时候报错

### ISSUE THREAD

**Issue by zhongchenyu** [debugtalk/ApiTestEngine#2]
> Failure
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python36-32\lib\unittest\suite.py", line 163, in _handleClassSetUp
    setUpClass()
  File "D:\autotest\python\ApiTestEngine\test\base.py", line 21, in setUpClass
    cls.api_server_process.start()
  File "D:\Program Files (x86)\Python36-32\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Program Files (x86)\Python36-32\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Program Files (x86)\Python36-32\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Program Files (x86)\Python36-32\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Program Files (x86)\Python36-32\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects

**Comment by debugtalk** [comment]
@zhongchenyu 确定运行方式正确

```bash
$ python -m unittest test.test_apiserver
```
