### ISSUE TITLE
运行ate -V时报错 pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by yileye** [debugtalk/ApiTestEngine#28]
Traceback (most recent call last):
  File "/Users/finup/gitlab/ApiTestEngine/env/bin/ate", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/finup/gitlab/ApiTestEngine/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/Users/finup/gitlab/ApiTestEngine/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/Users/finup/gitlab/ApiTestEngine/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/finup/gitlab/ApiTestEngine/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/Users/finup/gitlab/ApiTestEngine/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 972, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/finup/gitlab/ApiTestEngine/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ipaddress; python_version <= "2.7" and extra == "secure"' distribution was not found and is required by urllib3

**Comment by Junho2010** [comment]
pkg_resources.DistributionNotFound: The 'ipaddress; python_version <= "2.7" and extra == "secure"' distribution was not found and is required by urllib3

**Comment by debugtalk** [comment]
@yileye @Junho2010 已确定当前在`Python 2.7`上存在该问题，正在修复中。

**Comment by debugtalk** [comment]
@yileye @Junho2010 问题已修复。
