### ISSUE TITLE
判断的endswith有问题

### ISSUE THREAD

**Issue by Junho2010** [debugtalk/ApiTestEngine#31]
测试日志：
```text
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\ate\task.py", line 17, in runTest
    self.assertTrue(self.test_runner.run_test(self.testcase))
  File "C:\Python36\lib\site-packages\ate\runner.py", line 103, in run_test
    resp_obj.validate(validators, self.context.get_testcase_variables_mapping())
  File "C:\Python36\lib\site-packages\ate\response.py", line 121, in validate
    check_item
  File "C:\Python36\lib\site-packages\ate\utils.py", line 220, in match_expected
    raise exception.ValidationError(err_msg)
ate.exception.ValidationError: check item name: content.data.content.0.name;
check item value: admin (str);
comparator: endswith;
expected value: n (str).
```
源码：

```python
    elif comparator in ["endswith"]:
        assert str(expected).startswith(str(value))
    else:
        raise exception.ParamsError("comparator not supported!")
```

**Comment by debugtalk** [comment]
@Junho2010 fixed.
