### ISSUE TITLE
当接口没有返回值的时候，框架会抛出异常。

### ISSUE THREAD

**Issue by yileye** [debugtalk/ApiTestEngine#34]
```text
有这样一个使用场景
1.接口为请求数据的接口
2.接口没有返回任何数据，也就是消息体为空
```

这种情况下，框架会抛出一个异常
```text
======================================================================
ERROR [0.032409s]: Get zqDataContrast Data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/finup/gitlab/ApiTestEngine/ate/task.py", line 17, in runTest
    self.assertTrue(self.test_runner.run_test(self.testcase))
  File "/Users/finup/gitlab/ApiTestEngine/ate/runner.py", line 103, in run_test
    resp_obj.validate(validators, self.context.get_testcase_variables_mapping())
  File "/Users/finup/gitlab/ApiTestEngine/ate/response.py", line 115, in validate
    validator_dict["actual_value"] = self.extract_field(check_item)
  File "/Users/finup/gitlab/ApiTestEngine/ate/response.py", line 48, in extract_field
    return utils.query_json(json_content, sub_query)
  File "/Users/finup/gitlab/ApiTestEngine/ate/utils.py", line 151, in query_json
    print(json_content[key])
TypeError: string indices must be integers
```

我仔细看了一下源码，应该是这段

```python
try:
    for key in stripped_query.split(delimiter):
        if isinstance(json_content, list):
            key = int(key)
        json_content = json_content[key]
except (KeyError, ValueError, IndexError):
    raise exception.ParseResponseError("failed to query json when extracting response!")#
return json_content
```

```text
但是还没搞明白为什么会有这种异常？
```

**Comment by debugtalk** [comment]
@yileye 接口没有响应内容，这得看系统为啥没有返回了；建议你可以在运行接口测试的时候抓包看下，也有可能是构造的请求有问题。

另外，针对接口响应为空的问题，当前框架的确报错信息不明显，不应该是抛异常，而是报错提示接口响应为空；这个我完善下。

**Comment by debugtalk** [comment]
@yileye 你升级以后再试下。
