### ISSUE TITLE
【演示脚本test_apiserver.py运行错误】TypeError: can't pickle thread.lock objects 

### ISSUE THREAD

**Issue by firefoxwang** [debugtalk/ApiTestEngine#47]
【运行环境】:
    系统：win7 
    编辑器：pycharm2017
    软件环境：python2.7.13

【运行步骤】
    在pycharm里运行test_apiserver.py脚本 执行单元测试 报进程错误 
TypeError: can't pickle thread.lock objects 

 【错误回溯】
Failure
Traceback (most recent call last):
  File "D:\Python27\Lib\unittest\suite.py", line 146, in _handleClassSetUp
    setUpClass()
  File "D:\python_project\ApiTestEngine\tests\base.py", line 20, in setUpClass
    cls.api_server_process.start()
  File "D:\Python27\Lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "D:\Python27\Lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "D:\Python27\Lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "D:\Python27\Lib\pickle.py", line 224, in dump
    self.save(obj)
  File "D:\Python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "D:\Python27\Lib\pickle.py", line 425, in save_reduce
    save(state)
  File "D:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Python27\Lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "D:\Python27\Lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "D:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Python27\Lib\multiprocessing\forking.py", line 67, in dispatcher
    self.save_reduce(obj=obj, *rv)
  File "D:\Python27\Lib\pickle.py", line 401, in save_reduce
    save(args)
  File "D:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Python27\Lib\pickle.py", line 554, in save_tuple
    save(element)
  File "D:\Python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "D:\Python27\Lib\pickle.py", line 425, in save_reduce
    save(state)
  File "D:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Python27\Lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "D:\Python27\Lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "D:\Python27\Lib\pickle.py", line 306, in save
    rv = reduce(self.proto)
TypeError: can't pickle thread.lock objects

**Comment by firefoxwang** [comment]
我把Leo Lee大佬的代码一个一个的敲过来。当在熟悉[这篇文章](http://debugtalk.com/post/ApiTestEngine-0-setup-CI-test/)时，执行演示脚本test_apiserver.py报错。

**Comment by debugtalk** [comment]
@firefoxwang 这个问题之前也有人遇到过。但从报错堆栈来看，是Python的`pickle`出的问题，当前我也不知道问题在哪儿。建议换个Python版本再试下。

**Comment by firefoxwang** [comment]
找到问题的原因了，Process类的入参，target是需要“defined at the top-level of a module”。具体的可以[看这里](https://stackoverflow.com/questions/8804830/python-multiprocessing-pickling-error)，最高票回答的讲解。
『解决方法』: 1.在base.py脚本中添加
`def apprun():
    _ = api_server.app.run()`
2.修改test_apiserver.py的第十八行为 ` target=apprun`
